# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(950, 684)
        MainMenu.setMinimumSize(QtCore.QSize(950, 684))
        MainMenu.setMaximumSize(QtCore.QSize(950, 684))
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 951, 651))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Name = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(74)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Name.setFont(font)
        self.Name.setAlignment(QtCore.Qt.AlignCenter)
        self.Name.setObjectName("Name")
        self.verticalLayout_2.addWidget(self.Name)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Startbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.Startbutton.setMinimumSize(QtCore.QSize(0, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Startbutton.setFont(font)
        self.Startbutton.setObjectName("Startbutton")
        self.verticalLayout.addWidget(self.Startbutton)
        self.statisticbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.statisticbutton.setMinimumSize(QtCore.QSize(0, 46))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.statisticbutton.setFont(font)
        self.statisticbutton.setObjectName("statisticbutton")
        self.verticalLayout.addWidget(self.statisticbutton)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.player_counter_slider = QtWidgets.QSlider(self.layoutWidget)
        self.player_counter_slider.setMinimum(1)
        self.player_counter_slider.setMaximum(4)
        self.player_counter_slider.setPageStep(1)
        self.player_counter_slider.setProperty("value", 1)
        self.player_counter_slider.setOrientation(QtCore.Qt.Horizontal)
        self.player_counter_slider.setObjectName("player_counter_slider")
        self.verticalLayout.addWidget(self.player_counter_slider)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 21))
        self.menubar.setObjectName("menubar")
        MainMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainMenu)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "MainWindow"))
        self.Name.setText(_translate("MainMenu", "Snake"))
        self.Startbutton.setText(_translate("MainMenu", "Начать игру"))
        self.statisticbutton.setText(_translate("MainMenu", "Статисктика"))
        self.label.setText(_translate("MainMenu", "Количество игроков:1"))
