# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(554, 379)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(60, 50, 421, 221))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Name = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(36)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Name.setFont(font)
        self.Name.setAlignment(QtCore.Qt.AlignCenter)
        self.Name.setObjectName("Name")
        self.verticalLayout_2.addWidget(self.Name)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Startbutton = QtWidgets.QPushButton(self.widget)
        self.Startbutton.setObjectName("Startbutton")
        self.verticalLayout.addWidget(self.Startbutton)
        self.statisticbutton = QtWidgets.QPushButton(self.widget)
        self.statisticbutton.setObjectName("statisticbutton")
        self.verticalLayout.addWidget(self.statisticbutton)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.player_counter_slider = QtWidgets.QSlider(self.widget)
        self.player_counter_slider.setMinimum(1)
        self.player_counter_slider.setMaximum(4)
        self.player_counter_slider.setPageStep(1)
        self.player_counter_slider.setProperty("value", 1)
        self.player_counter_slider.setOrientation(QtCore.Qt.Horizontal)
        self.player_counter_slider.setObjectName("player_counter_slider")
        self.verticalLayout.addWidget(self.player_counter_slider)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 554, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Name.setText(_translate("MainWindow", "Snake"))
        self.Startbutton.setText(_translate("MainWindow", "Начать игру"))
        self.statisticbutton.setText(_translate("MainWindow", "Статисктика"))
        self.label.setText(_translate("MainWindow", "Количество игроков:1"))
