# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staticUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 900)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(25, 100, 950, 750))
        self.tableWidget.setMinimumSize(QtCore.QSize(950, 750))
        self.tableWidget.setMaximumSize(QtCore.QSize(950, 750))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.sort = QtWidgets.QComboBox(Dialog)
        self.sort.setGeometry(QtCore.QRect(40, 40, 391, 22))
        self.sort.setObjectName("sort")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
